apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-server-pv
  annotations:
    pv.kubernetes.io/bound-by-controller: "yes"
  finalizers:
  - kubernetes.io/pv-protection
spec:
  capacity:
    storage: 8Gi                   # Adjusted to match PVC
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /data/prometheus-server
    type: ""
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual          # Must match PVC's storageClassName (manual)
  claimRef:                         # Set to automatically bind to the PVC
    namespace: default
    name: prometheus-server
  volumeMode: Filesystem
status:
  phase: Available

