apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: portfolio-eks-cluster
  region: ap-south-1

nodeGroups:
- name: ng-1
  instanceType: t2.medium
  desiredCapacity: 1


# this will create a managed node of type t2 medium 
# eksctl create cluster -f filename.yaml
