# clusterissuer-lets-encrypt-staging.yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: portfolio-cert-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: sarvadnyajawle@gmail.com
    privateKeySecretRef:
      name: portfolio-private-key
    solvers:
    - http01:
        ingress:
          ingressClassName: nginx
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: portfolio-tls-certificate
  namespace: default
spec:
  secretName: portfolio-tls-cert # The certificate will be stored in this secret
  dnsNames:
  - sarvadnya.tech # Domain name to secure
  issuerRef:
    name: portfolio-cert-issuer # Reference to ClusterIssuer (created earlier)
    kind: ClusterIssuer
