apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: portfolio-http-route
spec:
  parentRefs:
  - name: portfolio-gateway
    sectionName: http
  hostnames:
  - "sarvadnya.tech"
  rules:
  - backendRefs:
    - name: portfolio-service
      kind: Service
      port: 80
    rules:
  - matches:
    - path:
        type: PathPrefix
        value: /home

