apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: portfolio-eks-cluster
  region: ap-south-1
  version: "1.30"
  tags:
    portfolio-eks-cluster: portfolio-eks-cluster
    env: portfolio-eks-cluster-stage
iam:
  withOIDC: true
vpc:
  cidr: 24.10.0.0/16
  clusterEndpoints:
    privateAccess: true
    publicAccess: true
addons:
- name: vpc-cni
  version: 1.16.0
  configurationValues: '{"env":{"ENABLE_PREFIX_DELEGATION":"true", "ENABLE_POD_ENI":"true", "POD_SECURITY_GROUP_ENFORCING_MODE":"standard"},"enableNetworkPolicy": "true", "nodeAgent": {"enablePolicyEventLogs": "true"}}'
  resolveConflicts: overwrite
managedNodeGroups:
- name: portfolio-eks-cluster-ng-1
  desiredCapacity: 1
  minSize: 1
  maxSize: 2
  instanceType: t2.medium
  privateNetworking: true
  releaseVersion: "1.30.0-20240625"
  updateConfig:
    maxUnavailablePercentage: 50
  labels:
    app: portfolio
