apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-server
spec:
  storageClassName: gp2  # Use the existing gp2 storage class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

