# clusterissuer-lets-encrypt-staging.yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: portfolio-cert-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: sarvadnyajawle@gmail.com
    privateKeySecretRef:
      name: portfolio-private-key
    solvers:
    - http01:
        ingress:
          ingressClassName: nginx
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: portfolio-tls-certificate
  namespace: default
spec:
  secretName: portfolio-tls-certificate # The certificate will be stored in this secret
  privateKey:
    rotationPolicy: Always # it will rotate private key just before certificate renewal!
  dnsNames:
  - sarvadnya.tech # Domain name to secure
  issuerRef:
    name: portfolio-cert-issuer # Reference to ClusterIssuer (created earlier)
    kind: ClusterIssuer
  duration: 2160h # Set certificate validity for 90 days (default)
  renewBefore: 360h # Renew the certificate 15 days before expiration
