apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: portfolio-eks-cluster-stage
  region: ap-south-1
  version: "1.30"
  tags:
    portfolio-eks-cluster: portfolio-eks-cluster
    env: portfolio-eks-cluster
nodeGroups:
- name: portfolio-eks-cluster-stage-ng
  instanceType: t2.medium
  desiredCapacity: 1
  minSize: 1
  maxSize: 10
  labels:
    app: portfolio
