apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: portfolio-eks-cluster
  region: ap-south-1

nodeGroups:
- name: portfolio-eks-cluster-ng
  instanceType: t2.large
  desiredCapacity: 2
  minSize: 1
  maxSize: 10
  labels:
    app: portfolio

# this will create a managed node of type t2 medium 
# eksctl create cluster -f filename.yaml
