name: Docker CI/CD Workflow

on:
  push:
    branches:
    - test # You have to do changes over here

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Docker Buildx.
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 3: Log in to Docker Hub.
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

    # Step 4: Build the Docker image.
    - name: Build Docker image
      run: |
        IMAGE_TAG=sarvadnya/portfolio:${{ github.sha }}
        docker build -t $IMAGE_TAG ./app
      env:
        COMMIT_HASH: ${{ github.sha }}

    - name: Scan Docker image with Trivy
      # Scan the Docker image with Trivy
      uses: aquasecurity/trivy-action@0.20.0
      with:
        image-ref: sarvadnya/portfolio:${{ github.sha }}
        format: table
        severity: HIGH,CRITICAL
        ignore-unfixed: true
        output: /home/ubuntu/trivy-report2.txt

    # Upload Trivy report as an artifact
    - name: Upload Trivy scan report
      uses: actions/upload-artifact@v3
      with:
        name: trivy-report
        path: /home/ubuntu/trivy-report2.txt

    # Step 5: Push the Docker image to Docker Hub.
    - name: Push Docker image
      if: success()
      run: |
        IMAGE_TAG=sarvadnya/portfolio:${{ github.sha }}
        docker push $IMAGE_TAG
      env:
        COMMIT_HASH: ${{ github.sha }}

    # Step 6: Deploy to EC2.
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # Pull the Docker image on the EC2 instance.
          IMAGE_TAG=sarvadnya/portfolio:${{ github.sha }}
          docker pull $IMAGE_TAG

          # Stop and remove the existing container if it exists.
          if [ "$(docker ps -q -f name=github-action-docker-image)" ]; then
            docker stop github-action-docker-image
            docker rm github-action-docker-image
          fi

          # Run the Docker container.
          docker run -d --name github-action-docker-image -p 8080:80 $IMAGE_TAG
      env:
        COMMIT_HASH: ${{ github.sha }}

